# Generated by Django 3.2 on 2023-04-30 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('class_name', models.CharField(db_index=True, max_length=32)),
            ],
            options={
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course_name', models.CharField(db_index=True, max_length=32)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'student_detail',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(db_index=True, max_length=32, verbose_name='学生姓名')),
                ('age', models.SmallIntegerField(default=0, verbose_name='年龄')),
                ('sex', models.SmallIntegerField(choices=[(0, '男生'), (1, '女生'), (2, '保密')], default=1, verbose_name='性别')),
                ('description', models.TextField(default='', verbose_name='个性签名')),
                ('courses', models.ManyToManyField(db_table='student_course', related_name='stu_course', to='orm_.Course')),
                ('details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stu_details', to='orm_.studentdetail')),
                ('stu_class', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='stu_class', to='orm_.classes')),
            ],
            options={
                'verbose_name': '学生信息表',
                'db_table': 'student',
            },
        ),
    ]
