# Generated by Django 3.2 on 2023-04-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(db_table='student_course', null=True, related_name='stu_course', to='orm_.Course'),
        ),
    ]
