# Generated by Django 3.2 on 2023-04-30 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm_', '0002_alter_student_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_class',
            field=models.ForeignKey(db_column='class_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_class', to='orm_.classes'),
        ),
    ]
